# $all: ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã®ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆã‚’æ‹¡å¼µã™ã‚‹
format = """
$all\
$directory\
$character
"""

palette = "catppuccin"

[directory]
format = "\uf07b  [$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
truncate_to_repo = true

[character]
success_symbol = "[â¯](bold red)[â¯](bold green)[â¯](bold blue)"
error_symbol = "[â¯â¯â¯](bold red)"

# languages
[nodejs]
format = 'Node.js [$symbol($version )]($style)'

[lua]
format = 'Lua [$symbol($version )]($style) '

[ruby]
format = 'Ruby [$symbol($version )]($style)'

[golang]
format = 'Golang [$symbol($version )]($style)'

[rust]
format = 'Rust [$symbol($version )]($style)'

# git
[git_branch]
format = "[$symbol$branch]($style) "

# others
[docker_context]
format = 'Docker [ğŸ‹ $context](blue bold)'

[aws]
disabled = true

# https://github.com/jx11r/archdots/blob/e24b54e272ee31e1c425f486ff0675f90a7cdf2c/.config/starship/starship.toml
[palettes.catppuccin]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
